//<editor-fold defaultstate="collapsed" desc="The MIT License">
/*
 * The MIT License
 *
 * Copyright 2021 Gabriel Pavan de Moura, João da Silva Nodari, 
 * João Guilherme Aragão and Luciana Balsaneli Scabini.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *///</editor-fold>
package view;

import controller.EmprestimosController;
import controller.LivrosController;
import controller.UsuariosController;
import java.awt.CardLayout;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @authors kayasuz, JoaoNodari and lucianabalsaneliscabini
 */
public class AdminView extends javax.swing.JFrame {
    private final CardLayout cardLayout;
    private final UsuariosController usuarios;
    private final LivrosController livros;
    private final EmprestimosController emprestimos;

    /**
     * Creates new form MenuView
     */
    public AdminView() {
        initComponents();
        cardLayout = (CardLayout) CardView.getLayout();
        usuarios = new UsuariosController(this);
        livros = new LivrosController(this);
        emprestimos = new EmprestimosController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtIdUsuario = new javax.swing.JTextField();
        FileChooser = new javax.swing.JFileChooser();
        Menu = new javax.swing.JPanel();
        LbLogo = new javax.swing.JLabel();
        BtnHome = new javax.swing.JButton();
        BtnLivros = new javax.swing.JButton();
        BtnUsuarios = new javax.swing.JButton();
        BtnEmprestimos = new javax.swing.JButton();
        BtnSair = new javax.swing.JButton();
        Separador = new javax.swing.JSeparator();
        CardView = new javax.swing.JPanel();
        cardHome = new javax.swing.JPanel();
        LbHome = new javax.swing.JLabel();
        LbBoasVindas = new javax.swing.JLabel();
        cardLivros = new javax.swing.JPanel();
        LbLivro = new javax.swing.JLabel();
        BoxLivro = new javax.swing.JPanel();
        LbNomeLivro = new javax.swing.JLabel();
        TxtNomeLivro = new javax.swing.JTextField();
        LbPublicacaoLivro = new javax.swing.JLabel();
        TxtPublicacaoLivro = new javax.swing.JTextField();
        SpnQuantidadeLivro = new javax.swing.JSpinner();
        LbCategoriaLivro = new javax.swing.JLabel();
        CmbBoxCategoriaLivro = new javax.swing.JComboBox<>();
        LbAutorLivro = new javax.swing.JLabel();
        CmbBoxAutorLivro = new javax.swing.JComboBox<>();
        BoxResumoLivro = new javax.swing.JPanel();
        ScrollResumo = new javax.swing.JScrollPane();
        TxtAreaResumoLivro = new javax.swing.JTextArea();
        BtnCapaLivro = new javax.swing.JButton();
        BtnAdicionarLivro = new javax.swing.JButton();
        PnlCapaLivro = new javax.swing.JPanel();
        LbCapaLivro = new javax.swing.JLabel();
        LbCategorias = new javax.swing.JLabel();
        BoxCategorias = new javax.swing.JPanel();
        ScrollCategorias = new javax.swing.JScrollPane();
        TbCategorias = new javax.swing.JTable();
        TxtIdCategoria = new javax.swing.JTextField();
        TxtCategoria = new javax.swing.JTextField();
        BtnAdicionarCategoria = new javax.swing.JButton();
        BtnRemoverCategoria = new javax.swing.JButton();
        LbAutores = new javax.swing.JLabel();
        BoxAutores = new javax.swing.JPanel();
        ScrollAutores = new javax.swing.JScrollPane();
        TbAutores = new javax.swing.JTable();
        TxtIdAutor = new javax.swing.JTextField();
        TxtAutor = new javax.swing.JTextField();
        BtnAdicionarAutor = new javax.swing.JButton();
        BtnRemoverAutor = new javax.swing.JButton();
        cardUsuarios = new javax.swing.JPanel();
        LbCadastro = new javax.swing.JLabel();
        BoxCadastro = new javax.swing.JPanel();
        LbNomeUsuario = new javax.swing.JLabel();
        TxtNomeUsuario = new javax.swing.JTextField();
        LbEmailUsuario = new javax.swing.JLabel();
        TxtEmailUsuario = new javax.swing.JTextField();
        LbEnderecoUsuario = new javax.swing.JLabel();
        TxtEnderecoUsuario = new javax.swing.JTextField();
        LbUsuario = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JTextField();
        LbSenhaUsuario = new javax.swing.JLabel();
        TxtSenhaUsuario = new javax.swing.JPasswordField();
        LbTelefoneUsuario = new javax.swing.JLabel();
        TxtTelefoneUsuario = new javax.swing.JFormattedTextField();
        BtnSalvarUsuario = new javax.swing.JButton();
        BtnLimparUsuario = new javax.swing.JButton();
        BtnExcluirUsuario = new javax.swing.JButton();
        LbUsuarios = new javax.swing.JLabel();
        BoxUsuarios = new javax.swing.JPanel();
        ScrollUsuarios = new javax.swing.JScrollPane();
        TbUsuarios = new javax.swing.JTable();
        cardEmprestimos = new javax.swing.JPanel();
        LbEmprestimos = new javax.swing.JLabel();
        BoxEmprestimos = new javax.swing.JPanel();
        LbClientes = new javax.swing.JLabel();
        ScrollClientes = new javax.swing.JScrollPane();
        TbClientes = new javax.swing.JTable();
        LbLivros = new javax.swing.JLabel();
        ScrollLivros = new javax.swing.JScrollPane();
        TbLivros = new javax.swing.JTable();
        BoxPedido = new javax.swing.JPanel();
        LbPedido = new javax.swing.JLabel();
        LbNomeCliente = new javax.swing.JLabel();
        TxtNomeCliente = new javax.swing.JTextField();
        LbAluguelCliente = new javax.swing.JLabel();
        TxtAluguelCliente = new javax.swing.JFormattedTextField();
        LbLivroCliente = new javax.swing.JLabel();
        TxtLivroCliente = new javax.swing.JTextField();
        LbDisponivelCliente = new javax.swing.JLabel();
        TxtDisponivelCliente = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        TxtIdUsuario.setEditable(false);
        TxtIdUsuario.setText("0");

        FileChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        FileChooser.setApproveButtonText("Enviar");
        FileChooser.setCurrentDirectory(new java.io.File("C:\\Users\\kayas\\Desktop\\APS-Java-card\\Biblioteca\\src\\view\\imagens\\livros"));
        FileChooser.setDialogTitle("Adicionar Capa");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Biblioteca JJLG - Administrador");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        Menu.setBackground(new java.awt.Color(204, 204, 204));

        LbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/JJLG.jpeg"))); // NOI18N
        LbLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BtnHome.setBackground(new java.awt.Color(255, 255, 255));
        BtnHome.setText("Home");
        BtnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnHome.setOpaque(false);
        BtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHomeActionPerformed(evt);
            }
        });

        BtnLivros.setBackground(new java.awt.Color(255, 255, 255));
        BtnLivros.setText("Gerenciar livros");
        BtnLivros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLivros.setOpaque(false);
        BtnLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLivrosActionPerformed(evt);
            }
        });

        BtnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        BtnUsuarios.setText("Gerenciar usuários");
        BtnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnUsuarios.setOpaque(false);
        BtnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUsuariosActionPerformed(evt);
            }
        });

        BtnEmprestimos.setBackground(new java.awt.Color(255, 255, 255));
        BtnEmprestimos.setText("Gerenciar empréstimos");
        BtnEmprestimos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEmprestimos.setOpaque(false);
        BtnEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEmprestimosActionPerformed(evt);
            }
        });

        BtnSair.setBackground(new java.awt.Color(255, 255, 255));
        BtnSair.setText("Logout");
        BtnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSair.setOpaque(false);
        BtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(LbLogo)
                    .addComponent(BtnSair)
                    .addComponent(BtnHome)
                    .addComponent(BtnLivros)
                    .addComponent(BtnUsuarios)
                    .addComponent(BtnEmprestimos))
                .addGap(50, 50, 50))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnEmprestimos, BtnHome, BtnLivros, BtnSair, BtnUsuarios});

        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(LbLogo)
                .addGap(18, 18, 18)
                .addComponent(BtnHome)
                .addGap(18, 18, 18)
                .addComponent(BtnLivros)
                .addGap(18, 18, 18)
                .addComponent(BtnUsuarios)
                .addGap(18, 18, 18)
                .addComponent(BtnEmprestimos)
                .addGap(18, 18, 18)
                .addComponent(BtnSair)
                .addGap(33, 33, 33))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnEmprestimos, BtnHome, BtnLivros, BtnSair, BtnUsuarios});

        Separador.setForeground(new java.awt.Color(0, 0, 0));
        Separador.setOrientation(javax.swing.SwingConstants.VERTICAL);

        CardView.setPreferredSize(new java.awt.Dimension(0, 0));
        CardView.setLayout(new java.awt.CardLayout());

        cardHome.setBackground(new java.awt.Color(255, 255, 255));

        LbHome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbHome.setText("Painel de Controle do Administrador");

        LbBoasVindas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LbBoasVindas.setText("Seja bem-vindo");

        javax.swing.GroupLayout cardHomeLayout = new javax.swing.GroupLayout(cardHome);
        cardHome.setLayout(cardHomeLayout);
        cardHomeLayout.setHorizontalGroup(
            cardHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardHomeLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(cardHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(LbBoasVindas)
                    .addComponent(LbHome))
                .addGap(110, 110, 110))
        );
        cardHomeLayout.setVerticalGroup(
            cardHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardHomeLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(LbHome)
                .addGap(18, 18, 18)
                .addComponent(LbBoasVindas)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        CardView.add(cardHome, "cardHome");

        cardLivros.setBackground(new java.awt.Color(255, 255, 255));
        cardLivros.setPreferredSize(new java.awt.Dimension(505, 490));

        LbLivro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbLivro.setText("Cadastrar novo livro");

        BoxLivro.setBackground(new java.awt.Color(255, 255, 255));
        BoxLivro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LbNomeLivro.setText("Nome:");

        LbPublicacaoLivro.setText("Publicação: ");

        SpnQuantidadeLivro.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        SpnQuantidadeLivro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LbCategoriaLivro.setText("Categoria:");

        CmbBoxCategoriaLivro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LbAutorLivro.setText("Autor:");

        CmbBoxAutorLivro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BoxResumoLivro.setBackground(new java.awt.Color(255, 255, 255));
        BoxResumoLivro.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumo"));
        BoxResumoLivro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        ScrollResumo.setViewportView(TxtAreaResumoLivro);

        javax.swing.GroupLayout BoxResumoLivroLayout = new javax.swing.GroupLayout(BoxResumoLivro);
        BoxResumoLivro.setLayout(BoxResumoLivroLayout);
        BoxResumoLivroLayout.setHorizontalGroup(
            BoxResumoLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollResumo, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
        );
        BoxResumoLivroLayout.setVerticalGroup(
            BoxResumoLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollResumo, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );

        BtnCapaLivro.setText("Add Capa");
        BtnCapaLivro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCapaLivro.setOpaque(false);
        BtnCapaLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCapaLivroActionPerformed(evt);
            }
        });

        BtnAdicionarLivro.setText("Adicionar");
        BtnAdicionarLivro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAdicionarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdicionarLivroActionPerformed(evt);
            }
        });

        PnlCapaLivro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout PnlCapaLivroLayout = new javax.swing.GroupLayout(PnlCapaLivro);
        PnlCapaLivro.setLayout(PnlCapaLivroLayout);
        PnlCapaLivroLayout.setHorizontalGroup(
            PnlCapaLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlCapaLivroLayout.createSequentialGroup()
                .addComponent(LbCapaLivro)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PnlCapaLivroLayout.setVerticalGroup(
            PnlCapaLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlCapaLivroLayout.createSequentialGroup()
                .addComponent(LbCapaLivro)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BoxLivroLayout = new javax.swing.GroupLayout(BoxLivro);
        BoxLivro.setLayout(BoxLivroLayout);
        BoxLivroLayout.setHorizontalGroup(
            BoxLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoxLivroLayout.createSequentialGroup()
                .addGroup(BoxLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BoxLivroLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(LbNomeLivro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbPublicacaoLivro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtPublicacaoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SpnQuantidadeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BoxLivroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BoxResumoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(BoxLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BoxLivroLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(BoxLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BoxLivroLayout.createSequentialGroup()
                                .addComponent(LbCategoriaLivro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CmbBoxCategoriaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BoxLivroLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(LbAutorLivro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CmbBoxAutorLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BoxLivroLayout.createSequentialGroup()
                                .addComponent(BtnCapaLivro)
                                .addGap(2, 2, 2)
                                .addComponent(BtnAdicionarLivro))))
                    .addGroup(BoxLivroLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(PnlCapaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13))
        );
        BoxLivroLayout.setVerticalGroup(
            BoxLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoxLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BoxLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNomeLivro)
                    .addComponent(TxtNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbPublicacaoLivro)
                    .addComponent(CmbBoxCategoriaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbCategoriaLivro)
                    .addComponent(SpnQuantidadeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtPublicacaoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoxLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BoxLivroLayout.createSequentialGroup()
                        .addComponent(BoxResumoLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(BoxLivroLayout.createSequentialGroup()
                        .addGroup(BoxLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CmbBoxAutorLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbAutorLivro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BoxLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnCapaLivro)
                            .addComponent(BtnAdicionarLivro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PnlCapaLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        LbCategorias.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbCategorias.setText("Categorias");

        BoxCategorias.setBackground(new java.awt.Color(255, 255, 255));
        BoxCategorias.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TbCategorias.setAutoCreateRowSorter(true);
        TbCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Categorias"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TbCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbCategoriasMouseClicked(evt);
            }
        });
        ScrollCategorias.setViewportView(TbCategorias);

        TxtIdCategoria.setEditable(false);
        TxtIdCategoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtIdCategoria.setText("0");

        BtnAdicionarCategoria.setText("Adicionar");
        BtnAdicionarCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAdicionarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdicionarCategoriaActionPerformed(evt);
            }
        });

        BtnRemoverCategoria.setText("Remover");
        BtnRemoverCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRemoverCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRemoverCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BoxCategoriasLayout = new javax.swing.GroupLayout(BoxCategorias);
        BoxCategorias.setLayout(BoxCategoriasLayout);
        BoxCategoriasLayout.setHorizontalGroup(
            BoxCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoxCategoriasLayout.createSequentialGroup()
                .addGroup(BoxCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(BoxCategoriasLayout.createSequentialGroup()
                        .addComponent(BtnAdicionarCategoria)
                        .addGap(18, 18, 18)
                        .addComponent(BtnRemoverCategoria))
                    .addComponent(ScrollCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(BoxCategoriasLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(TxtIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TxtCategoria)
                .addContainerGap())
        );

        BoxCategoriasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnAdicionarCategoria, BtnRemoverCategoria});

        BoxCategoriasLayout.setVerticalGroup(
            BoxCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoxCategoriasLayout.createSequentialGroup()
                .addComponent(ScrollCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoxCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoxCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRemoverCategoria)
                    .addComponent(BtnAdicionarCategoria)))
        );

        BoxCategoriasLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnAdicionarCategoria, BtnRemoverCategoria});

        LbAutores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbAutores.setText("Autores");

        BoxAutores.setBackground(new java.awt.Color(255, 255, 255));
        BoxAutores.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TbAutores.setAutoCreateRowSorter(true);
        TbAutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Autores"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbAutores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TbAutores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbAutoresMouseClicked(evt);
            }
        });
        ScrollAutores.setViewportView(TbAutores);

        TxtIdAutor.setEditable(false);
        TxtIdAutor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtIdAutor.setText("0");

        BtnAdicionarAutor.setText("Adicionar");
        BtnAdicionarAutor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAdicionarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdicionarAutorActionPerformed(evt);
            }
        });

        BtnRemoverAutor.setText("Remover");
        BtnRemoverAutor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRemoverAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRemoverAutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BoxAutoresLayout = new javax.swing.GroupLayout(BoxAutores);
        BoxAutores.setLayout(BoxAutoresLayout);
        BoxAutoresLayout.setHorizontalGroup(
            BoxAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoxAutoresLayout.createSequentialGroup()
                .addGroup(BoxAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BoxAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(BoxAutoresLayout.createSequentialGroup()
                            .addComponent(BtnAdicionarAutor)
                            .addGap(18, 18, 18)
                            .addComponent(BtnRemoverAutor))
                        .addComponent(ScrollAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BoxAutoresLayout.createSequentialGroup()
                        .addComponent(TxtIdAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TxtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        BoxAutoresLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnAdicionarAutor, BtnRemoverAutor});

        BoxAutoresLayout.setVerticalGroup(
            BoxAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoxAutoresLayout.createSequentialGroup()
                .addComponent(ScrollAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoxAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtIdAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoxAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAdicionarAutor)
                    .addComponent(BtnRemoverAutor)))
        );

        BoxAutoresLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnAdicionarAutor, BtnRemoverAutor});

        javax.swing.GroupLayout cardLivrosLayout = new javax.swing.GroupLayout(cardLivros);
        cardLivros.setLayout(cardLivrosLayout);
        cardLivrosLayout.setHorizontalGroup(
            cardLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLivrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cardLivrosLayout.createSequentialGroup()
                        .addGroup(cardLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbCategorias)
                            .addComponent(BoxCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cardLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbAutores)
                            .addComponent(BoxAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(LbLivro)
                    .addComponent(BoxLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardLivrosLayout.setVerticalGroup(
            cardLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLivrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbLivro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BoxLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbAutores)
                    .addComponent(LbCategorias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoxCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CardView.add(cardLivros, "cardLivros");

        cardUsuarios.setBackground(new java.awt.Color(255, 255, 255));

        LbCadastro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbCadastro.setText("Cadastrar novo usuário");

        BoxCadastro.setBackground(new java.awt.Color(255, 255, 255));
        BoxCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LbNomeUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LbNomeUsuario.setText("Nome");

        LbEmailUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LbEmailUsuario.setText("Email");

        LbEnderecoUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LbEnderecoUsuario.setText("Endereço");

        LbUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LbUsuario.setText("Usuário");

        LbSenhaUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LbSenhaUsuario.setText("Senha");

        LbTelefoneUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LbTelefoneUsuario.setText("Telefone");

        try {
            TxtTelefoneUsuario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        BtnSalvarUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnSalvarUsuario.setText("Salvar");
        BtnSalvarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSalvarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarUsuarioActionPerformed(evt);
            }
        });

        BtnLimparUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnLimparUsuario.setText("Limpar");
        BtnLimparUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLimparUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparUsuarioActionPerformed(evt);
            }
        });

        BtnExcluirUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnExcluirUsuario.setText("Excluir");
        BtnExcluirUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BoxCadastroLayout = new javax.swing.GroupLayout(BoxCadastro);
        BoxCadastro.setLayout(BoxCadastroLayout);
        BoxCadastroLayout.setHorizontalGroup(
            BoxCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoxCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BoxCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LbNomeUsuario)
                    .addComponent(LbEmailUsuario)
                    .addComponent(LbEnderecoUsuario)
                    .addComponent(TxtNomeUsuario)
                    .addComponent(TxtEmailUsuario)
                    .addComponent(TxtEnderecoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BoxCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtUsuario)
                    .addComponent(LbUsuario)
                    .addComponent(LbSenhaUsuario)
                    .addComponent(TxtSenhaUsuario)
                    .addComponent(LbTelefoneUsuario)
                    .addComponent(TxtTelefoneUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(BoxCadastroLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(BtnSalvarUsuario)
                .addGap(18, 18, 18)
                .addComponent(BtnLimparUsuario)
                .addGap(18, 18, 18)
                .addComponent(BtnExcluirUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BoxCadastroLayout.setVerticalGroup(
            BoxCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoxCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BoxCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNomeUsuario)
                    .addComponent(LbUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoxCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BoxCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbEmailUsuario)
                    .addComponent(LbSenhaUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoxCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEmailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BoxCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbEnderecoUsuario)
                    .addComponent(LbTelefoneUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoxCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEnderecoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTelefoneUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BoxCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(BtnLimparUsuario)
                    .addComponent(BtnSalvarUsuario)
                    .addComponent(BtnExcluirUsuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LbUsuarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbUsuarios.setText("Alterar usuários");

        BoxUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        BoxUsuarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TbUsuarios.setAutoCreateRowSorter(true);
        TbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Email", "Endereço", "Usuário", "Senha", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TbUsuarios.getTableHeader().setReorderingAllowed(false);
        TbUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbUsuariosMouseClicked(evt);
            }
        });
        ScrollUsuarios.setViewportView(TbUsuarios);

        javax.swing.GroupLayout BoxUsuariosLayout = new javax.swing.GroupLayout(BoxUsuarios);
        BoxUsuarios.setLayout(BoxUsuariosLayout);
        BoxUsuariosLayout.setHorizontalGroup(
            BoxUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        BoxUsuariosLayout.setVerticalGroup(
            BoxUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout cardUsuariosLayout = new javax.swing.GroupLayout(cardUsuarios);
        cardUsuarios.setLayout(cardUsuariosLayout);
        cardUsuariosLayout.setHorizontalGroup(
            cardUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoxCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BoxUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(cardUsuariosLayout.createSequentialGroup()
                        .addGroup(cardUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbUsuarios)
                            .addComponent(LbCadastro))
                        .addGap(0, 302, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cardUsuariosLayout.setVerticalGroup(
            cardUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoxCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoxUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        CardView.add(cardUsuarios, "cardUsuarios");

        cardEmprestimos.setBackground(new java.awt.Color(255, 255, 255));
        cardEmprestimos.setPreferredSize(new java.awt.Dimension(507, 490));

        LbEmprestimos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbEmprestimos.setText("Cadastrar novo empréstimo");

        BoxEmprestimos.setBackground(new java.awt.Color(255, 255, 255));
        BoxEmprestimos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LbClientes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LbClientes.setText("Selecionar Cliente");

        ScrollClientes.setBackground(new java.awt.Color(255, 255, 255));

        TbClientes.setAutoCreateRowSorter(true);
        TbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Nº Aluguéis"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TbClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ScrollClientes.setViewportView(TbClientes);

        LbLivros.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LbLivros.setText("Selecionar Livro");

        ScrollLivros.setBackground(new java.awt.Color(255, 255, 255));

        TbLivros.setAutoCreateRowSorter(true);
        TbLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TbLivros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ScrollLivros.setViewportView(TbLivros);

        javax.swing.GroupLayout BoxEmprestimosLayout = new javax.swing.GroupLayout(BoxEmprestimos);
        BoxEmprestimos.setLayout(BoxEmprestimosLayout);
        BoxEmprestimosLayout.setHorizontalGroup(
            BoxEmprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoxEmprestimosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BoxEmprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(LbClientes)
                    .addComponent(ScrollClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(BoxEmprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(LbLivros)
                    .addComponent(ScrollLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        BoxEmprestimosLayout.setVerticalGroup(
            BoxEmprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoxEmprestimosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BoxEmprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbClientes)
                    .addComponent(LbLivros))
                .addGap(13, 13, 13)
                .addGroup(BoxEmprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(ScrollLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        BoxPedido.setBackground(new java.awt.Color(255, 255, 255));
        BoxPedido.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LbPedido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LbPedido.setText("Dados do Pedido");

        LbNomeCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LbNomeCliente.setText("ID Cliente:");

        LbAluguelCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LbAluguelCliente.setText("Data Aluguel:");

        TxtAluguelCliente.setColumns(10);
        try {
            TxtAluguelCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## / ## / ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxtAluguelCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        LbLivroCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LbLivroCliente.setText("ID Livro: ");

        LbDisponivelCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LbDisponivelCliente.setText("Disponíveis:");

        TxtDisponivelCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Salvar pedido");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BoxPedidoLayout = new javax.swing.GroupLayout(BoxPedido);
        BoxPedido.setLayout(BoxPedidoLayout);
        BoxPedidoLayout.setHorizontalGroup(
            BoxPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoxPedidoLayout.createSequentialGroup()
                .addGroup(BoxPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BoxPedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(BoxPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BoxPedidoLayout.createSequentialGroup()
                                .addGroup(BoxPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(BoxPedidoLayout.createSequentialGroup()
                                        .addComponent(LbNomeCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(BoxPedidoLayout.createSequentialGroup()
                                        .addComponent(LbAluguelCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtAluguelCliente)))
                                .addGap(26, 26, 26)
                                .addGroup(BoxPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbLivroCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LbDisponivelCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(BoxPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TxtDisponivelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtLivroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(LbPedido)))
                    .addGroup(BoxPedidoLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BoxPedidoLayout.setVerticalGroup(
            BoxPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoxPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BoxPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNomeCliente)
                    .addComponent(TxtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbLivroCliente)
                    .addComponent(TxtLivroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BoxPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDisponivelCliente)
                    .addComponent(TxtDisponivelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbAluguelCliente)
                    .addComponent(TxtAluguelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout cardEmprestimosLayout = new javax.swing.GroupLayout(cardEmprestimos);
        cardEmprestimos.setLayout(cardEmprestimosLayout);
        cardEmprestimosLayout.setHorizontalGroup(
            cardEmprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardEmprestimosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardEmprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardEmprestimosLayout.createSequentialGroup()
                        .addComponent(LbEmprestimos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(BoxEmprestimos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BoxPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        cardEmprestimosLayout.setVerticalGroup(
            cardEmprestimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardEmprestimosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbEmprestimos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoxEmprestimos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BoxPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CardView.add(cardEmprestimos, "cardEmprestimos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Separador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CardView, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Separador, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(CardView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHomeActionPerformed
        cardLayout.show(CardView, "cardHome");
    }//GEN-LAST:event_BtnHomeActionPerformed

    private void BtnLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLivrosActionPerformed
        cardLayout.show(CardView, "cardLivros");
        livros.mostraCategorias();
        livros.mostraAutores();
    }//GEN-LAST:event_BtnLivrosActionPerformed

    private void BtnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUsuariosActionPerformed
        cardLayout.show(CardView, "cardUsuarios");
        usuarios.mostraUsuarios();
    }//GEN-LAST:event_BtnUsuariosActionPerformed

    private void BtnEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEmprestimosActionPerformed
        cardLayout.show(CardView, "cardEmprestimos");
        emprestimos.mostraClientes();
        emprestimos.mostraLivros();
    }//GEN-LAST:event_BtnEmprestimosActionPerformed

    private void BtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSairActionPerformed
        usuarios.sair();
    }//GEN-LAST:event_BtnSairActionPerformed

    private void BtnCapaLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCapaLivroActionPerformed
        livros.adicionaCapa();
    }//GEN-LAST:event_BtnCapaLivroActionPerformed

    private void BtnAdicionarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdicionarLivroActionPerformed
        livros.salvaLivro();
    }//GEN-LAST:event_BtnAdicionarLivroActionPerformed

    private void BtnAdicionarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdicionarCategoriaActionPerformed
        livros.adicionaCategoria();
    }//GEN-LAST:event_BtnAdicionarCategoriaActionPerformed

    private void BtnRemoverCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRemoverCategoriaActionPerformed
        livros.excluiCategoria();
    }//GEN-LAST:event_BtnRemoverCategoriaActionPerformed

    private void BtnAdicionarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdicionarAutorActionPerformed
        livros.adicionaAutor();
    }//GEN-LAST:event_BtnAdicionarAutorActionPerformed

    private void BtnRemoverAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRemoverAutorActionPerformed
        livros.excluiAutor();
    }//GEN-LAST:event_BtnRemoverAutorActionPerformed

    private void BtnSalvarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarUsuarioActionPerformed
        usuarios.salvaUsuario();
    }//GEN-LAST:event_BtnSalvarUsuarioActionPerformed

    private void BtnLimparUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparUsuarioActionPerformed
        usuarios.limpaCampos();
    }//GEN-LAST:event_BtnLimparUsuarioActionPerformed

    private void BtnExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirUsuarioActionPerformed
        usuarios.excluiUsuario();
    }//GEN-LAST:event_BtnExcluirUsuarioActionPerformed

    private void TbCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbCategoriasMouseClicked
        livros.selecionaCategorias();
    }//GEN-LAST:event_TbCategoriasMouseClicked

    private void TbAutoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbAutoresMouseClicked
        livros.selecionaAutores();
    }//GEN-LAST:event_TbAutoresMouseClicked

    private void TbUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbUsuariosMouseClicked
        usuarios.selecionaUsuario();
    }//GEN-LAST:event_TbUsuariosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        emprestimos.salvar();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }//</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminView().setVisible(true);
        });
    }

    //<editor-fold defaultstate="collapsed" desc="Getters e Setters - cardLivros">
    public JTextField getTxtNomeLivro() { return TxtNomeLivro; }
    public void setTxtNomeLivro(JTextField TxtNomeLivro) { this.TxtNomeLivro = TxtNomeLivro; }

    public JTextField getTxtPublicacaoLivro() { return TxtPublicacaoLivro; }
    public void setTxtPublicacaoLivro(JFormattedTextField TxtPublicacaoLivro) { this.TxtPublicacaoLivro = TxtPublicacaoLivro; }

    public JSpinner getSpnQuantidadeLivro() { return SpnQuantidadeLivro; }
    public void setSpnQuantidadeLivro(JSpinner SpnQuantidadeLivro) { this.SpnQuantidadeLivro = SpnQuantidadeLivro; }

    public JComboBox<String> getCmbBoxCategoriaLivro() { return CmbBoxCategoriaLivro; }
    public void setCmbBoxCategoriaLivro(JComboBox<String> CmbBoxCategoriaLivro) { this.CmbBoxCategoriaLivro = CmbBoxCategoriaLivro; }

    public JComboBox<String> getCmbBoxAutorLivro() { return CmbBoxAutorLivro; }
    public void setCmbBoxAutorLivro(JComboBox<String> CmbBoxAutorLivro) { this.CmbBoxAutorLivro = CmbBoxAutorLivro; }

    public JTextArea getTxtAreaResumoLivro() { return TxtAreaResumoLivro; }
    public void setTxtAreaResumoLivro(JTextArea TxtAreaResumoLivro) { this.TxtAreaResumoLivro = TxtAreaResumoLivro; }

    public JTextField getTxtAutor() { return TxtAutor; }
    public void setTxtAutor(JTextField TxtAutor) { this.TxtAutor = TxtAutor; }

    public JTextField getTxtCategoria() { return TxtCategoria; }
    public void setTxtCategoria(JTextField TxtCategoria) { this.TxtCategoria = TxtCategoria; }

    public JTextField getTxtIdAutor() { return TxtIdAutor; }
    public void setTxtIdAutor(JTextField TxtIdAutor) { this.TxtIdAutor = TxtIdAutor; }

    public JTextField getTxtIdCategoria() { return TxtIdCategoria; }
    public void setTxtIdCategoria(JTextField TxtIdCategoria) { this.TxtIdCategoria = TxtIdCategoria; }

    public JTable getTbAutores() { return TbAutores; }
    public void setTbAutores(JTable TbAutores) { this.TbAutores = TbAutores; }

    public JTable getTbCategorias() { return TbCategorias; }
    public void setTbCategorias(JTable TbCategorias) { this.TbCategorias = TbCategorias; }

    public JTable getTbClientes() { return TbClientes; }
    public void setTbClientes(JTable TbClientes) { this.TbClientes = TbClientes; }

    public JTable getTbLivros() { return TbLivros; }
    public void setTbLivros(JTable TbLivros) { this.TbLivros = TbLivros; }

    public JLabel getLbCapaLivro() { return LbCapaLivro; }
    public void setLbCapaLivro(JLabel LbCapaLivro) { this.LbCapaLivro = LbCapaLivro; }

    public JFileChooser getFileChooser() { return FileChooser; }
    public void setFileChooser(JFileChooser FileChooser) { this.FileChooser = FileChooser; }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Getters e Setters - cardUsuarios">
    public JTextField getTxtIdUsuario() { return TxtIdUsuario; }
    public void setTxtIdUsuario(JTextField TxtIdUsuario) { this.TxtIdUsuario = TxtIdUsuario; }

    public JTextField getTxtUsuario() { return TxtUsuario; }
    public void setTxtUsuario(JTextField TxtUsuario) { this.TxtUsuario = TxtUsuario; }

    public JPasswordField getTxtSenhaUsuario() { return TxtSenhaUsuario; }
    public void setTxtSenhaUsuario(JPasswordField TxtSenhaUsuario) { this.TxtSenhaUsuario = TxtSenhaUsuario; }

    public JTextField getTxtNomeUsuario() { return TxtNomeUsuario; }
    public void setTxtNomeUsuario(JTextField TxtNomeUsuario) { this.TxtNomeUsuario = TxtNomeUsuario; }

    public JTextField getTxtEmailUsuario() { return TxtEmailUsuario; }
    public void setTxtEmailUsuario(JTextField TxtEmailUsuario) { this.TxtEmailUsuario = TxtEmailUsuario; }

    public JTextField getTxtEnderecoUsuario() { return TxtEnderecoUsuario; }
    public void setTxtEnderecoUsuario(JTextField TxtEnderecoUsuario) { this.TxtEnderecoUsuario = TxtEnderecoUsuario; }

    public JFormattedTextField getTxtTelefoneUsuario() { return TxtTelefoneUsuario; }
    public void setTxtTelefoneUsuario(JFormattedTextField TxtTelefoneUsuario) { this.TxtTelefoneUsuario = TxtTelefoneUsuario; }

    public JTable getTbUsuarios() { return TbUsuarios; }
    public void setTbUsuarios(JTable TbUsuarios) { this.TbUsuarios = TbUsuarios; }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Getters e Setters - cardEmprestimos">
    public JTextField getTxtNomeCliente() { return TxtNomeCliente; }
    public void setTxtNomeCliente(JTextField TxtNomeCliente) { this.TxtNomeCliente = TxtNomeCliente; }

    public JTextField getTxtLivroCliente() { return TxtLivroCliente; }
    public void setTxtLivroCliente(JTextField TxtLivroCliente) { this.TxtLivroCliente = TxtLivroCliente; }

    public JTextField getTxtDisponivelCliente() { return TxtDisponivelCliente; }
    public void setTxtDisponivelCliente(JTextField TxtDisponivelCliente) { this.TxtDisponivelCliente = TxtDisponivelCliente; }

    public JFormattedTextField getTxtAluguelCliente() { return TxtAluguelCliente; }
    public void setTxtAluguelCliente(JFormattedTextField TxtAluguelCliente) { this.TxtAluguelCliente = TxtAluguelCliente; }
    //</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BoxAutores;
    private javax.swing.JPanel BoxCadastro;
    private javax.swing.JPanel BoxCategorias;
    private javax.swing.JPanel BoxEmprestimos;
    private javax.swing.JPanel BoxLivro;
    private javax.swing.JPanel BoxPedido;
    private javax.swing.JPanel BoxResumoLivro;
    private javax.swing.JPanel BoxUsuarios;
    private javax.swing.JButton BtnAdicionarAutor;
    private javax.swing.JButton BtnAdicionarCategoria;
    private javax.swing.JButton BtnAdicionarLivro;
    private javax.swing.JButton BtnCapaLivro;
    private javax.swing.JButton BtnEmprestimos;
    private javax.swing.JButton BtnExcluirUsuario;
    private javax.swing.JButton BtnHome;
    private javax.swing.JButton BtnLimparUsuario;
    private javax.swing.JButton BtnLivros;
    private javax.swing.JButton BtnRemoverAutor;
    private javax.swing.JButton BtnRemoverCategoria;
    private javax.swing.JButton BtnSair;
    private javax.swing.JButton BtnSalvarUsuario;
    private javax.swing.JButton BtnUsuarios;
    private javax.swing.JPanel CardView;
    private javax.swing.JComboBox<String> CmbBoxAutorLivro;
    private javax.swing.JComboBox<String> CmbBoxCategoriaLivro;
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JLabel LbAluguelCliente;
    private javax.swing.JLabel LbAutorLivro;
    private javax.swing.JLabel LbAutores;
    private javax.swing.JLabel LbBoasVindas;
    private javax.swing.JLabel LbCadastro;
    private javax.swing.JLabel LbCapaLivro;
    private javax.swing.JLabel LbCategoriaLivro;
    private javax.swing.JLabel LbCategorias;
    private javax.swing.JLabel LbClientes;
    private javax.swing.JLabel LbDisponivelCliente;
    private javax.swing.JLabel LbEmailUsuario;
    private javax.swing.JLabel LbEmprestimos;
    private javax.swing.JLabel LbEnderecoUsuario;
    private javax.swing.JLabel LbHome;
    private javax.swing.JLabel LbLivro;
    private javax.swing.JLabel LbLivroCliente;
    private javax.swing.JLabel LbLivros;
    private javax.swing.JLabel LbLogo;
    private javax.swing.JLabel LbNomeCliente;
    private javax.swing.JLabel LbNomeLivro;
    private javax.swing.JLabel LbNomeUsuario;
    private javax.swing.JLabel LbPedido;
    private javax.swing.JLabel LbPublicacaoLivro;
    private javax.swing.JLabel LbSenhaUsuario;
    private javax.swing.JLabel LbTelefoneUsuario;
    private javax.swing.JLabel LbUsuario;
    private javax.swing.JLabel LbUsuarios;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel PnlCapaLivro;
    private javax.swing.JScrollPane ScrollAutores;
    private javax.swing.JScrollPane ScrollCategorias;
    private javax.swing.JScrollPane ScrollClientes;
    private javax.swing.JScrollPane ScrollLivros;
    private javax.swing.JScrollPane ScrollResumo;
    private javax.swing.JScrollPane ScrollUsuarios;
    private javax.swing.JSeparator Separador;
    private javax.swing.JSpinner SpnQuantidadeLivro;
    private javax.swing.JTable TbAutores;
    private javax.swing.JTable TbCategorias;
    private javax.swing.JTable TbClientes;
    private javax.swing.JTable TbLivros;
    private javax.swing.JTable TbUsuarios;
    private javax.swing.JFormattedTextField TxtAluguelCliente;
    private javax.swing.JTextArea TxtAreaResumoLivro;
    private javax.swing.JTextField TxtAutor;
    private javax.swing.JTextField TxtCategoria;
    private javax.swing.JTextField TxtDisponivelCliente;
    private javax.swing.JTextField TxtEmailUsuario;
    private javax.swing.JTextField TxtEnderecoUsuario;
    private javax.swing.JTextField TxtIdAutor;
    private javax.swing.JTextField TxtIdCategoria;
    private javax.swing.JTextField TxtIdUsuario;
    private javax.swing.JTextField TxtLivroCliente;
    private javax.swing.JTextField TxtNomeCliente;
    private javax.swing.JTextField TxtNomeLivro;
    private javax.swing.JTextField TxtNomeUsuario;
    private javax.swing.JTextField TxtPublicacaoLivro;
    private javax.swing.JPasswordField TxtSenhaUsuario;
    private javax.swing.JFormattedTextField TxtTelefoneUsuario;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JPanel cardEmprestimos;
    private javax.swing.JPanel cardHome;
    private javax.swing.JPanel cardLivros;
    private javax.swing.JPanel cardUsuarios;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
