//<editor-fold defaultstate="collapsed" desc="The MIT License">
/*
 * The MIT License
 *
 * Copyright 2021 Gabriel Pavan de Moura, João da Silva Nodari, 
 * João Guilherme Aragão and Luciana Balsaneli Scabini.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *///</editor-fold>
package view;

import controller.FormCadastroController;
import javax.swing.JFormattedTextField;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @authors kayas, joaon, lucib, ?
 */
public class AdminViewUsuarios extends javax.swing.JFrame {
    
    private final FormCadastroController controller;
    
    /**
     * Creates new form MenuView
     */
    public AdminViewUsuarios() {
        initComponents();
        controller = new FormCadastroController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxId = new javax.swing.JTextField();
        SptMenu = new javax.swing.JSeparator();
        PainelMenu = new javax.swing.JPanel();
        LbLogo = new javax.swing.JLabel();
        BtnSair = new javax.swing.JButton();
        TgBtnHome = new javax.swing.JToggleButton();
        TgBtnLivros = new javax.swing.JToggleButton();
        TgBtnUsuarios = new javax.swing.JToggleButton();
        TgBtnEmprestimos = new javax.swing.JToggleButton();
        PainelUsuarios = new javax.swing.JPanel();
        LbCadastro = new javax.swing.JLabel();
        BoxDadosCadastro = new javax.swing.JPanel();
        LbNome = new javax.swing.JLabel();
        TxtNome = new javax.swing.JTextField();
        LbEmail = new javax.swing.JLabel();
        TxtEmail = new javax.swing.JTextField();
        LbEndereco = new javax.swing.JLabel();
        TxtEndereco = new javax.swing.JTextField();
        LbUsuario = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JTextField();
        LbSenha = new javax.swing.JLabel();
        TxtSenha = new javax.swing.JPasswordField();
        LbTelefone = new javax.swing.JLabel();
        TxtTelefone = new javax.swing.JFormattedTextField();
        BtnSalvar = new javax.swing.JButton();
        BtnLimpar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        LbAlterar = new javax.swing.JLabel();
        BoxDadosUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        TxId.setEditable(false);
        TxId.setEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador - Gerenciar usuários");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        SptMenu.setForeground(new java.awt.Color(0, 0, 0));
        SptMenu.setOrientation(javax.swing.SwingConstants.VERTICAL);

        PainelMenu.setBackground(new java.awt.Color(204, 204, 204));

        LbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/JJLG-icon.jpeg"))); // NOI18N
        LbLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BtnSair.setBackground(new java.awt.Color(255, 255, 255));
        BtnSair.setText("Sair");
        BtnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSair.setOpaque(false);
        BtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSairActionPerformed(evt);
            }
        });

        TgBtnHome.setBackground(new java.awt.Color(255, 255, 255));
        TgBtnHome.setText("Home");
        TgBtnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TgBtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TgBtnHomeActionPerformed(evt);
            }
        });

        TgBtnLivros.setBackground(new java.awt.Color(255, 255, 255));
        TgBtnLivros.setText("Gerenciar livros");
        TgBtnLivros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TgBtnLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TgBtnLivrosActionPerformed(evt);
            }
        });

        TgBtnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        TgBtnUsuarios.setText("Gerenciar usuários");
        TgBtnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TgBtnUsuarios.setEnabled(false);

        TgBtnEmprestimos.setBackground(new java.awt.Color(255, 255, 255));
        TgBtnEmprestimos.setText("Gerenciar empréstimos");
        TgBtnEmprestimos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TgBtnEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TgBtnEmprestimosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelMenuLayout = new javax.swing.GroupLayout(PainelMenu);
        PainelMenu.setLayout(PainelMenuLayout);
        PainelMenuLayout.setHorizontalGroup(
            PainelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelMenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(PainelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(LbLogo)
                    .addComponent(BtnSair)
                    .addComponent(TgBtnHome)
                    .addComponent(TgBtnLivros)
                    .addComponent(TgBtnUsuarios)
                    .addComponent(TgBtnEmprestimos))
                .addGap(50, 50, 50))
        );

        PainelMenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnSair, TgBtnEmprestimos, TgBtnHome, TgBtnLivros, TgBtnUsuarios});

        PainelMenuLayout.setVerticalGroup(
            PainelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(LbLogo)
                .addGap(18, 18, 18)
                .addComponent(TgBtnHome)
                .addGap(18, 18, 18)
                .addComponent(TgBtnLivros)
                .addGap(18, 18, 18)
                .addComponent(TgBtnUsuarios)
                .addGap(18, 18, 18)
                .addComponent(TgBtnEmprestimos)
                .addGap(18, 18, 18)
                .addComponent(BtnSair)
                .addGap(33, 33, 33))
        );

        PainelMenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnSair, TgBtnEmprestimos, TgBtnHome, TgBtnLivros, TgBtnUsuarios});

        PainelUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        PainelUsuarios.setPreferredSize(new java.awt.Dimension(504, 36));

        LbCadastro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LbCadastro.setText("Cadastrar novo usuário");

        BoxDadosCadastro.setBackground(new java.awt.Color(255, 255, 255));
        BoxDadosCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LbNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LbNome.setText("Nome");

        LbEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LbEmail.setText("Email");

        LbEndereco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LbEndereco.setText("Endereço");

        LbUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LbUsuario.setText("Usuário");

        LbSenha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LbSenha.setText("Senha");

        LbTelefone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LbTelefone.setText("Telefone");

        try {
            TxtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        BtnSalvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnSalvar.setText("Salvar");
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        BtnLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnLimpar.setText("Limpar");
        BtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setText("Alterar");

        jButton2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton2.setText("Excluir");

        javax.swing.GroupLayout BoxDadosCadastroLayout = new javax.swing.GroupLayout(BoxDadosCadastro);
        BoxDadosCadastro.setLayout(BoxDadosCadastroLayout);
        BoxDadosCadastroLayout.setHorizontalGroup(
            BoxDadosCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoxDadosCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BoxDadosCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LbNome)
                    .addComponent(LbEmail)
                    .addComponent(LbEndereco)
                    .addComponent(TxtNome)
                    .addComponent(TxtEmail)
                    .addComponent(TxtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BoxDadosCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtUsuario)
                    .addComponent(LbUsuario)
                    .addComponent(LbSenha)
                    .addComponent(TxtSenha)
                    .addComponent(LbTelefone)
                    .addComponent(TxtTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(BoxDadosCadastroLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(BtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BoxDadosCadastroLayout.setVerticalGroup(
            BoxDadosCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoxDadosCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BoxDadosCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNome)
                    .addComponent(LbUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoxDadosCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BoxDadosCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbEmail)
                    .addComponent(LbSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoxDadosCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BoxDadosCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbEndereco)
                    .addComponent(LbTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoxDadosCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BoxDadosCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSalvar)
                    .addComponent(BtnLimpar)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LbAlterar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LbAlterar.setText("Alterar usuários");

        BoxDadosUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        BoxDadosUsuarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Email", "Endereço", "Usuário", "Senha", "Telefone"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout BoxDadosUsuariosLayout = new javax.swing.GroupLayout(BoxDadosUsuarios);
        BoxDadosUsuarios.setLayout(BoxDadosUsuariosLayout);
        BoxDadosUsuariosLayout.setHorizontalGroup(
            BoxDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoxDadosUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addContainerGap())
        );
        BoxDadosUsuariosLayout.setVerticalGroup(
            BoxDadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoxDadosUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PainelUsuariosLayout = new javax.swing.GroupLayout(PainelUsuarios);
        PainelUsuarios.setLayout(PainelUsuariosLayout);
        PainelUsuariosLayout.setHorizontalGroup(
            PainelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoxDadosCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PainelUsuariosLayout.createSequentialGroup()
                        .addGroup(PainelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbCadastro)
                            .addComponent(LbAlterar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(BoxDadosUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PainelUsuariosLayout.setVerticalGroup(
            PainelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoxDadosCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoxDadosUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SptMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SptMenu, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(PainelUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TgBtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TgBtnHomeActionPerformed
        dispose();
        new AdminViewHome().setVisible(true);
    }//GEN-LAST:event_TgBtnHomeActionPerformed

    private void TgBtnLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TgBtnLivrosActionPerformed
        dispose();
        new AdminViewLivros().setVisible(true);
    }//GEN-LAST:event_TgBtnLivrosActionPerformed

    private void TgBtnEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TgBtnEmprestimosActionPerformed
        dispose();
        new AdminViewEmprestimos().setVisible(true);
    }//GEN-LAST:event_TgBtnEmprestimosActionPerformed

    private void BtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSairActionPerformed
        dispose();
    }//GEN-LAST:event_BtnSairActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        controller.salvaUsuario();
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void BtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparActionPerformed
        TxtNome.setText(null);
        TxtEmail.setText(null);
        TxtEndereco.setText(null);
        TxtUsuario.setText(null);
        TxtSenha.setText(null);
        TxtTelefone.setText(null);
    }//GEN-LAST:event_BtnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }//</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminViewUsuarios().setVisible(true);
        });
    }

    public JTextField getTxId() { return TxId; }
    public void setTxId(JTextField TxId) { this.TxId = TxId; }

    public JTextField getTxtNome() { return TxtNome; }
    public void setTxtNome(JTextField TxtNome) { this.TxtNome = TxtNome; }

    public JTextField getTxtEmail() { return TxtEmail; }
    public void setTxtEmail(JTextField TxtEmail) { this.TxtEmail = TxtEmail; }

    public JTextField getTxtEndereco() { return TxtEndereco; }
    public void setTxtEndereco(JTextField TxtEndereco) { this.TxtEndereco = TxtEndereco; }

    public JTextField getTxtUsuario() { return TxtUsuario; }
    public void setTxtUsuario(JTextField TxtUsuario) { this.TxtUsuario = TxtUsuario; }

    public JPasswordField getTxtSenha() { return TxtSenha; }
    public void setTxtSenha(JPasswordField TxtSenha) { this.TxtSenha = TxtSenha; }

    public JFormattedTextField getTxtTelefone() { return TxtTelefone; }
    public void setTxtTelefone(JFormattedTextField TxtTelefone) { this.TxtTelefone = TxtTelefone; }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BoxDadosCadastro;
    private javax.swing.JPanel BoxDadosUsuarios;
    private javax.swing.JButton BtnLimpar;
    private javax.swing.JButton BtnSair;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JLabel LbAlterar;
    private javax.swing.JLabel LbCadastro;
    private javax.swing.JLabel LbEmail;
    private javax.swing.JLabel LbEndereco;
    private javax.swing.JLabel LbLogo;
    private javax.swing.JLabel LbNome;
    private javax.swing.JLabel LbSenha;
    private javax.swing.JLabel LbTelefone;
    private javax.swing.JLabel LbUsuario;
    private javax.swing.JPanel PainelMenu;
    private javax.swing.JPanel PainelUsuarios;
    private javax.swing.JSeparator SptMenu;
    private javax.swing.JToggleButton TgBtnEmprestimos;
    private javax.swing.JToggleButton TgBtnHome;
    private javax.swing.JToggleButton TgBtnLivros;
    private javax.swing.JToggleButton TgBtnUsuarios;
    private javax.swing.JTextField TxId;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtEndereco;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JPasswordField TxtSenha;
    private javax.swing.JFormattedTextField TxtTelefone;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
