/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.FormCadastroController;
import dao.Conexao;
import dao.UsuarioDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import model.Usuario;

public class MenuViewUsuarios extends javax.swing.JFrame {

    private final FormCadastroController controller;
    
    /**
     * Creates new form MenuView
     */
    public MenuViewUsuarios() {
        initComponents();
            controller = new FormCadastroController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SptMenu = new javax.swing.JSeparator();
        BtnHome = new javax.swing.JButton();
        BtnLivros = new javax.swing.JButton();
        BtnUsuarios = new javax.swing.JButton();
        BtnEmprestimos = new javax.swing.JButton();
        BtnSair = new javax.swing.JButton();
        LbLogo = new javax.swing.JLabel();
        LbTitulo1 = new javax.swing.JLabel();
        LbUsuario = new javax.swing.JLabel();
        LbSenha = new javax.swing.JLabel();
        TgBtnLimpar = new javax.swing.JToggleButton();
        TxtNome = new javax.swing.JTextField();
        TxtSenha = new javax.swing.JPasswordField();
        TxtEndereco = new javax.swing.JTextField();
        TxtTelefone = new javax.swing.JFormattedTextField();
        LbNome = new javax.swing.JLabel();
        TxtEmail = new javax.swing.JTextField();
        LbEmail = new javax.swing.JLabel();
        LbEndereco = new javax.swing.JLabel();
        TgBtnSalvar = new javax.swing.JToggleButton();
        LbTelefone = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JTextField();
        LbTitulo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 51));

        SptMenu.setForeground(new java.awt.Color(0, 0, 0));
        SptMenu.setOrientation(javax.swing.SwingConstants.VERTICAL);

        BtnHome.setText("Home");
        BtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHomeActionPerformed(evt);
            }
        });

        BtnLivros.setText("Gerenciar livros");
        BtnLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLivrosActionPerformed(evt);
            }
        });

        BtnUsuarios.setText("Gerenciar usuários");

        BtnEmprestimos.setText("Gerenciar empréstimos");
        BtnEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEmprestimosActionPerformed(evt);
            }
        });

        BtnSair.setText("Sair");
        BtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSairActionPerformed(evt);
            }
        });

        LbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/WhatsApp Image 2021-03-23 at 00.02.38.jpeg"))); // NOI18N
        LbLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LbTitulo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbTitulo1.setText("Cadastrar novo usuário");

        LbUsuario.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        LbUsuario.setText("Usuário");

        LbSenha.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        LbSenha.setText("Senha");

        TgBtnLimpar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        TgBtnLimpar.setText("Limpar");

        TxtSenha.setToolTipText("");

        TxtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEnderecoActionPerformed(evt);
            }
        });

        try {
            TxtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxtTelefone.setToolTipText("");

        LbNome.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        LbNome.setText("Nome");

        TxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEmailActionPerformed(evt);
            }
        });

        LbEmail.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        LbEmail.setText("Email");

        LbEndereco.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        LbEndereco.setText("Endereço");

        TgBtnSalvar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        TgBtnSalvar.setText("Salvar");
        TgBtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TgBtnSalvarActionPerformed(evt);
            }
        });

        LbTelefone.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        LbTelefone.setText("Telefone");

        LbTitulo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbTitulo2.setText("Alterar usuários");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(BtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEmprestimos)
                    .addComponent(BtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbLogo))
                .addGap(50, 50, 50)
                .addComponent(SptMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbTitulo2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LbNome)
                                    .addComponent(TxtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(LbEndereco)
                                    .addComponent(LbTitulo1)
                                    .addComponent(LbEmail)
                                    .addComponent(TxtEmail)
                                    .addComponent(TxtEndereco))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LbTelefone)
                                    .addComponent(LbUsuario)
                                    .addComponent(LbSenha)
                                    .addComponent(TxtUsuario)
                                    .addComponent(TxtSenha)
                                    .addComponent(TxtTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                .addGap(40, 40, 40))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(TgBtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addComponent(TgBtnLimpar)
                        .addGap(109, 109, 109))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SptMenu, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LbLogo)
                .addGap(18, 18, 18)
                .addComponent(BtnHome)
                .addGap(18, 18, 18)
                .addComponent(BtnLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnEmprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbTitulo1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbUsuario)
                    .addComponent(LbNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbSenha)
                    .addComponent(LbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbTelefone)
                    .addComponent(LbEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TgBtnSalvar)
                    .addComponent(TgBtnLimpar))
                .addGap(18, 18, 18)
                .addComponent(LbTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHomeActionPerformed
        new MenuViewHome().setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnHomeActionPerformed

    private void BtnLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLivrosActionPerformed
        new MenuViewLivros().setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnLivrosActionPerformed

    private void BtnEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEmprestimosActionPerformed
        new MenuViewEmprestimos().setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnEmprestimosActionPerformed

    private void BtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSairActionPerformed
        dispose();
    }//GEN-LAST:event_BtnSairActionPerformed

    private void TxtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEnderecoActionPerformed

    private void TxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEmailActionPerformed

    private void TgBtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TgBtnSalvarActionPerformed
        controller.salvaUsuario();
    }//GEN-LAST:event_TgBtnSalvarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuViewUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuViewUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuViewUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuViewUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuViewUsuarios().setVisible(true);
            }
        });
    }

    public JTextField getTxtEmail() {
        return TxtEmail;
    }

    public void setTxtEmail(JTextField txtEmail) {
        this.TxtEmail = txtEmail;
    }

    public JTextField getTxtEndereco() {
        return TxtEndereco;
    }

    public void setTxtEndereco(JTextField txtEndereco) {
        this.TxtEndereco = txtEndereco;
    }

    public JTextField getTxtNome() {
        return TxtNome;
    }

    public void setTxtNome(JTextField txtNome) {
        this.TxtNome = txtNome;
    }

    public JPasswordField getTxtSenha() {
        return TxtSenha;
    }

    public void setTxtSenha(JPasswordField txtSenha) {
        this.TxtSenha = txtSenha;
    }

    public JFormattedTextField getTxtTelefone() {
        return TxtTelefone;
    }

    public void setTxtTelefone(JFormattedTextField txtTelefone) {
        this.TxtTelefone = txtTelefone;
    }

    public JTextField getTxtUsuario() {
        return TxtUsuario;
    }

    public void setTxtUsuario(JTextField txtUsuario) {
        this.TxtUsuario = txtUsuario;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEmprestimos;
    private javax.swing.JButton BtnHome;
    private javax.swing.JButton BtnLivros;
    private javax.swing.JButton BtnSair;
    private javax.swing.JButton BtnUsuarios;
    private javax.swing.JLabel LbEmail;
    private javax.swing.JLabel LbEndereco;
    private javax.swing.JLabel LbLogo;
    private javax.swing.JLabel LbNome;
    private javax.swing.JLabel LbSenha;
    private javax.swing.JLabel LbTelefone;
    private javax.swing.JLabel LbTitulo1;
    private javax.swing.JLabel LbTitulo2;
    private javax.swing.JLabel LbUsuario;
    private javax.swing.JSeparator SptMenu;
    private javax.swing.JToggleButton TgBtnLimpar;
    private javax.swing.JToggleButton TgBtnSalvar;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtEndereco;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JPasswordField TxtSenha;
    private javax.swing.JFormattedTextField TxtTelefone;
    private javax.swing.JTextField TxtUsuario;
    // End of variables declaration//GEN-END:variables
}
