/*
 * The MIT License
 *
 * Copyright 2021 lucib.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package view;

import java.awt.CardLayout;
import java.awt.Color;

public class UserViewHome extends javax.swing.JFrame {

    /**
     * Creates new form UserViewHome
     */
    
    CardLayout cardLayout;
    
    public UserViewHome() {
        initComponents();
        
        cardLayout = (CardLayout)(painelMutavel.getLayout());
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SptMenu = new javax.swing.JSeparator();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        botaoDestaquesDeHoje = new javax.swing.JButton();
        botaoAutoAjuda = new javax.swing.JButton();
        botaoEducacional = new javax.swing.JButton();
        botaoFantasia = new javax.swing.JButton();
        botaoSuspense = new javax.swing.JButton();
        botaoRomance = new javax.swing.JButton();
        botaoDistopia = new javax.swing.JButton();
        botaoTerror = new javax.swing.JButton();
        botaoMeuPerfil = new javax.swing.JButton();
        botaoHistorico = new javax.swing.JButton();
        botaoCarrinho = new javax.swing.JButton();
        botaoLogout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botaoFiccao = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        painelMutavel = new javax.swing.JPanel();
        cardDestaquesDeHoje = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        cardAutoAjuda = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        cardEducacional = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        cardFantasia = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        cardSuspense = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        cardRomance = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        cardComedia = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        cardTerror = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        cardFiccao = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        cardCarrinho = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        botaoExcluirItem = new javax.swing.JButton();
        botaoSolicitarAluguel = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        cardHistorico = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        botaoCulinaria1 = new javax.swing.JButton();
        cardMeuPerfil = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();

        SptMenu.setForeground(new java.awt.Color(0, 0, 0));
        SptMenu.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pesquisar");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Gerenciamento");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Categorias");

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));

        botaoDestaquesDeHoje.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        botaoDestaquesDeHoje.setText("Destaques de Hoje");
        botaoDestaquesDeHoje.setBorderPainted(false);
        botaoDestaquesDeHoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDestaquesDeHojeActionPerformed(evt);
            }
        });

        botaoAutoAjuda.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        botaoAutoAjuda.setText("Auto Ajuda");
        botaoAutoAjuda.setBorderPainted(false);
        botaoAutoAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAutoAjudaActionPerformed(evt);
            }
        });

        botaoEducacional.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        botaoEducacional.setText("Educacional");
        botaoEducacional.setBorderPainted(false);
        botaoEducacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEducacionalActionPerformed(evt);
            }
        });

        botaoFantasia.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        botaoFantasia.setText("Fantasia");
        botaoFantasia.setBorderPainted(false);
        botaoFantasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFantasiaActionPerformed(evt);
            }
        });

        botaoSuspense.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        botaoSuspense.setText("Suspense");
        botaoSuspense.setBorderPainted(false);
        botaoSuspense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSuspenseActionPerformed(evt);
            }
        });

        botaoRomance.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        botaoRomance.setText("Romance");
        botaoRomance.setBorderPainted(false);
        botaoRomance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRomanceActionPerformed(evt);
            }
        });

        botaoDistopia.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        botaoDistopia.setText("Distopia");
        botaoDistopia.setBorderPainted(false);
        botaoDistopia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDistopiaActionPerformed(evt);
            }
        });

        botaoTerror.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        botaoTerror.setText("Terror");
        botaoTerror.setBorderPainted(false);
        botaoTerror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTerrorActionPerformed(evt);
            }
        });

        botaoMeuPerfil.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        botaoMeuPerfil.setText("Meu Perfil");
        botaoMeuPerfil.setBorderPainted(false);
        botaoMeuPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMeuPerfilActionPerformed(evt);
            }
        });

        botaoHistorico.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        botaoHistorico.setText("Histórico");
        botaoHistorico.setBorderPainted(false);
        botaoHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoHistoricoActionPerformed(evt);
            }
        });

        botaoCarrinho.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        botaoCarrinho.setText("Carrinho");
        botaoCarrinho.setBorderPainted(false);
        botaoCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCarrinhoActionPerformed(evt);
            }
        });

        botaoLogout.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        botaoLogout.setText("Logout");
        botaoLogout.setBorderPainted(false);
        botaoLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLogoutActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Bem-Vindo(a)");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nome Completo do Usuário");

        botaoFiccao.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        botaoFiccao.setText("Ficção");
        botaoFiccao.setBorderPainted(false);
        botaoFiccao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFiccaoActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/open-book.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botaoDestaquesDeHoje, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 10, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(botaoHistorico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoMeuPerfil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(botaoEducacional, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoFantasia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoSuspense, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(botaoFiccao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoCarrinho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botaoLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(botaoRomance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botaoDistopia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botaoTerror, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botaoAutoAjuda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoDestaquesDeHoje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoRomance)
                    .addComponent(botaoFiccao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEducacional)
                    .addComponent(botaoDistopia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoFantasia)
                    .addComponent(botaoTerror))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSuspense)
                    .addComponent(botaoAutoAjuda))
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoMeuPerfil)
                    .addComponent(botaoCarrinho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoHistorico)
                    .addComponent(botaoLogout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelMutavel.setBackground(new java.awt.Color(255, 255, 255));
        painelMutavel.setLayout(new java.awt.CardLayout());

        cardDestaquesDeHoje.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Destaques de Hoje");

        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/star.png"))); // NOI18N

        javax.swing.GroupLayout cardDestaquesDeHojeLayout = new javax.swing.GroupLayout(cardDestaquesDeHoje);
        cardDestaquesDeHoje.setLayout(cardDestaquesDeHojeLayout);
        cardDestaquesDeHojeLayout.setHorizontalGroup(
            cardDestaquesDeHojeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardDestaquesDeHojeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardDestaquesDeHojeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator14)
                    .addGroup(cardDestaquesDeHojeLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(0, 383, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cardDestaquesDeHojeLayout.setVerticalGroup(
            cardDestaquesDeHojeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardDestaquesDeHojeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardDestaquesDeHojeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(648, Short.MAX_VALUE))
        );

        painelMutavel.add(cardDestaquesDeHoje, "cardDestaquesDeHoje");

        cardAutoAjuda.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Auto Ajuda");

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/pessoas.png"))); // NOI18N

        javax.swing.GroupLayout cardAutoAjudaLayout = new javax.swing.GroupLayout(cardAutoAjuda);
        cardAutoAjuda.setLayout(cardAutoAjudaLayout);
        cardAutoAjudaLayout.setHorizontalGroup(
            cardAutoAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAutoAjudaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardAutoAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addGroup(cardAutoAjudaLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(0, 474, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cardAutoAjudaLayout.setVerticalGroup(
            cardAutoAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAutoAjudaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardAutoAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(644, Short.MAX_VALUE))
        );

        painelMutavel.add(cardAutoAjuda, "cardAutoAjuda");

        cardEducacional.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Educacional");

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/abra-o-livro.png"))); // NOI18N

        javax.swing.GroupLayout cardEducacionalLayout = new javax.swing.GroupLayout(cardEducacional);
        cardEducacional.setLayout(cardEducacionalLayout);
        cardEducacionalLayout.setHorizontalGroup(
            cardEducacionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardEducacionalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardEducacionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5)
                    .addGroup(cardEducacionalLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(0, 463, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cardEducacionalLayout.setVerticalGroup(
            cardEducacionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardEducacionalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardEducacionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(648, Short.MAX_VALUE))
        );

        painelMutavel.add(cardEducacional, "cardEducacional");

        cardFantasia.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Fantasia");

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/fantasia.png"))); // NOI18N

        javax.swing.GroupLayout cardFantasiaLayout = new javax.swing.GroupLayout(cardFantasia);
        cardFantasia.setLayout(cardFantasiaLayout);
        cardFantasiaLayout.setHorizontalGroup(
            cardFantasiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardFantasiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardFantasiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6)
                    .addGroup(cardFantasiaLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(0, 506, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cardFantasiaLayout.setVerticalGroup(
            cardFantasiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardFantasiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardFantasiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(648, Short.MAX_VALUE))
        );

        painelMutavel.add(cardFantasia, "cardFantasia");

        cardSuspense.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Suspense");

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/suspense.png"))); // NOI18N

        javax.swing.GroupLayout cardSuspenseLayout = new javax.swing.GroupLayout(cardSuspense);
        cardSuspense.setLayout(cardSuspenseLayout);
        cardSuspenseLayout.setHorizontalGroup(
            cardSuspenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardSuspenseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardSuspenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator7)
                    .addGroup(cardSuspenseLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(0, 494, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cardSuspenseLayout.setVerticalGroup(
            cardSuspenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardSuspenseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardSuspenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(648, Short.MAX_VALUE))
        );

        painelMutavel.add(cardSuspense, "cardSuspense");

        cardRomance.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Romance");

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/em-forma-de-coracao-com-detalhes-de-forro-branco.png"))); // NOI18N

        javax.swing.GroupLayout cardRomanceLayout = new javax.swing.GroupLayout(cardRomance);
        cardRomance.setLayout(cardRomanceLayout);
        cardRomanceLayout.setHorizontalGroup(
            cardRomanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardRomanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardRomanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator8)
                    .addGroup(cardRomanceLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(0, 495, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cardRomanceLayout.setVerticalGroup(
            cardRomanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardRomanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardRomanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(648, Short.MAX_VALUE))
        );

        painelMutavel.add(cardRomance, "cardRomance");

        cardComedia.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Distopia");

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/manipulacao.png"))); // NOI18N

        javax.swing.GroupLayout cardComediaLayout = new javax.swing.GroupLayout(cardComedia);
        cardComedia.setLayout(cardComediaLayout);
        cardComediaLayout.setHorizontalGroup(
            cardComediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardComediaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardComediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator9)
                    .addGroup(cardComediaLayout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(0, 508, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cardComediaLayout.setVerticalGroup(
            cardComediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardComediaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardComediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(645, Short.MAX_VALUE))
        );

        painelMutavel.add(cardComedia, "cardDistopia");

        cardTerror.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Terror");

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/fantasma.png"))); // NOI18N

        javax.swing.GroupLayout cardTerrorLayout = new javax.swing.GroupLayout(cardTerror);
        cardTerror.setLayout(cardTerrorLayout);
        cardTerrorLayout.setHorizontalGroup(
            cardTerrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardTerrorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardTerrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator10)
                    .addGroup(cardTerrorLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(0, 532, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cardTerrorLayout.setVerticalGroup(
            cardTerrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardTerrorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardTerrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(648, Short.MAX_VALUE))
        );

        painelMutavel.add(cardTerror, "cardTerror");

        cardFiccao.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Ficção");

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));

        jLabel34.setIcon(new javax.swing.ImageIcon("C:\\Users\\lucib\\Documents\\NetBeansProjects\\APS-Java\\Biblioteca\\src\\view\\imagens\\ficcao-cientifica.png")); // NOI18N

        javax.swing.GroupLayout cardFiccaoLayout = new javax.swing.GroupLayout(cardFiccao);
        cardFiccao.setLayout(cardFiccaoLayout);
        cardFiccaoLayout.setHorizontalGroup(
            cardFiccaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardFiccaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardFiccaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator11)
                    .addGroup(cardFiccaoLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(0, 530, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cardFiccaoLayout.setVerticalGroup(
            cardFiccaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardFiccaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardFiccaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(648, Short.MAX_VALUE))
        );

        painelMutavel.add(cardFiccao, "cardFiccao");

        cardCarrinho.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setText("Carrinho");

        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/carrinho-de-compras.png"))); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pedido", "ID Livro", "Nome do Livro", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        botaoExcluirItem.setBackground(new java.awt.Color(102, 102, 102));
        botaoExcluirItem.setForeground(new java.awt.Color(255, 255, 255));
        botaoExcluirItem.setText("Excluir Item");
        botaoExcluirItem.setBorderPainted(false);
        botaoExcluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirItemActionPerformed(evt);
            }
        });

        botaoSolicitarAluguel.setBackground(new java.awt.Color(102, 102, 102));
        botaoSolicitarAluguel.setForeground(new java.awt.Color(255, 255, 255));
        botaoSolicitarAluguel.setText("Solicitar Aluguel");
        botaoSolicitarAluguel.setBorderPainted(false);
        botaoSolicitarAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSolicitarAluguelActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel32.setText("Livros no Carrinho");

        javax.swing.GroupLayout cardCarrinhoLayout = new javax.swing.GroupLayout(cardCarrinho);
        cardCarrinho.setLayout(cardCarrinhoLayout);
        cardCarrinhoLayout.setHorizontalGroup(
            cardCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardCarrinhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cardCarrinhoLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addContainerGap(514, Short.MAX_VALUE))))
            .addGroup(cardCarrinhoLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(botaoExcluirItem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoSolicitarAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(cardCarrinhoLayout.createSequentialGroup()
                .addGroup(cardCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardCarrinhoLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardCarrinhoLayout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel32)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardCarrinhoLayout.setVerticalGroup(
            cardCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardCarrinhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(cardCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSolicitarAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoExcluirItem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(215, 215, 215))
        );

        painelMutavel.add(cardCarrinho, "cardCarrinho");

        cardHistorico.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setText("Histórico de Pedidos");

        jSeparator12.setBackground(new java.awt.Color(0, 0, 0));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/lista-de-afazeres.png"))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome Livro", "Data Aluguel", "Data Devolução", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Alugado", "Em Análise", "Reprovado", "Devolvido", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setText("Filtrar por:");

        botaoCulinaria1.setBackground(new java.awt.Color(102, 102, 102));
        botaoCulinaria1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoCulinaria1.setForeground(new java.awt.Color(255, 255, 255));
        botaoCulinaria1.setText("Pesquisar");
        botaoCulinaria1.setBorderPainted(false);
        botaoCulinaria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCulinaria1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardHistoricoLayout = new javax.swing.GroupLayout(cardHistorico);
        cardHistorico.setLayout(cardHistoricoLayout);
        cardHistoricoLayout.setHorizontalGroup(
            cardHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardHistoricoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator12)
                    .addGroup(cardHistoricoLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addGap(0, 362, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardHistoricoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(cardHistoricoLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel36)
                .addGap(14, 14, 14)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCulinaria1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardHistoricoLayout.setVerticalGroup(
            cardHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardHistoricoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addGroup(cardHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel36)
                    .addGroup(cardHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoCulinaria1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(324, Short.MAX_VALUE))
        );

        painelMutavel.add(cardHistorico, "cardHistorico");

        cardMeuPerfil.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 11))); // NOI18N
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Nome: ");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Endereço:");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("Email:");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setText("Telefone: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addContainerGap(372, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jLabel20.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel20.setText("Seu Perfil");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/perfil.png"))); // NOI18N

        jSeparator15.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout cardMeuPerfilLayout = new javax.swing.GroupLayout(cardMeuPerfil);
        cardMeuPerfil.setLayout(cardMeuPerfilLayout);
        cardMeuPerfilLayout.setHorizontalGroup(
            cardMeuPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardMeuPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardMeuPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cardMeuPerfilLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(cardMeuPerfilLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        cardMeuPerfilLayout.setVerticalGroup(
            cardMeuPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardMeuPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardMeuPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(385, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleName("dados");

        painelMutavel.add(cardMeuPerfil, "cardMeuPerfil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelMutavel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelMutavel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFiccaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFiccaoActionPerformed
        cardLayout.show(painelMutavel, "cardFiccao");
    }//GEN-LAST:event_botaoFiccaoActionPerformed

    private void botaoLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLogoutActionPerformed
        new LoginView().setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoLogoutActionPerformed

    private void botaoCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCarrinhoActionPerformed
        cardLayout.show(painelMutavel, "cardCarrinho");
    }//GEN-LAST:event_botaoCarrinhoActionPerformed

    private void botaoHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoHistoricoActionPerformed
        cardLayout.show(painelMutavel, "cardHistorico");
    }//GEN-LAST:event_botaoHistoricoActionPerformed

    private void botaoMeuPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMeuPerfilActionPerformed
        cardLayout.show(painelMutavel, "cardMeuPerfil");
    }//GEN-LAST:event_botaoMeuPerfilActionPerformed

    private void botaoTerrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTerrorActionPerformed
        cardLayout.show(painelMutavel, "cardTerror");
    }//GEN-LAST:event_botaoTerrorActionPerformed

    private void botaoDistopiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDistopiaActionPerformed
        cardLayout.show(painelMutavel, "cardDistopia");
    }//GEN-LAST:event_botaoDistopiaActionPerformed

    private void botaoRomanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRomanceActionPerformed
        cardLayout.show(painelMutavel, "cardRomance");
    }//GEN-LAST:event_botaoRomanceActionPerformed

    private void botaoSuspenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSuspenseActionPerformed
        cardLayout.show(painelMutavel, "cardSuspense");
    }//GEN-LAST:event_botaoSuspenseActionPerformed

    private void botaoFantasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFantasiaActionPerformed
        cardLayout.show(painelMutavel, "cardFantasia");
    }//GEN-LAST:event_botaoFantasiaActionPerformed

    private void botaoEducacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEducacionalActionPerformed
        cardLayout.show(painelMutavel, "cardEducacional");
    }//GEN-LAST:event_botaoEducacionalActionPerformed

    private void botaoAutoAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAutoAjudaActionPerformed
        cardLayout.show(painelMutavel, "cardAutoAjuda");
    }//GEN-LAST:event_botaoAutoAjudaActionPerformed

    private void botaoDestaquesDeHojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDestaquesDeHojeActionPerformed
       cardLayout.show(painelMutavel, "cardDestaquesDeHoje");
    }//GEN-LAST:event_botaoDestaquesDeHojeActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void botaoExcluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoExcluirItemActionPerformed

    private void botaoSolicitarAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSolicitarAluguelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSolicitarAluguelActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void botaoCulinaria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCulinaria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCulinaria1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserViewHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator SptMenu;
    private javax.swing.JButton botaoAutoAjuda;
    private javax.swing.JButton botaoCarrinho;
    private javax.swing.JButton botaoCulinaria1;
    private javax.swing.JButton botaoDestaquesDeHoje;
    private javax.swing.JButton botaoDistopia;
    private javax.swing.JButton botaoEducacional;
    private javax.swing.JButton botaoExcluirItem;
    private javax.swing.JButton botaoFantasia;
    private javax.swing.JButton botaoFiccao;
    private javax.swing.JButton botaoHistorico;
    private javax.swing.JButton botaoLogout;
    private javax.swing.JButton botaoMeuPerfil;
    private javax.swing.JButton botaoRomance;
    private javax.swing.JButton botaoSolicitarAluguel;
    private javax.swing.JButton botaoSuspense;
    private javax.swing.JButton botaoTerror;
    private javax.swing.JPanel cardAutoAjuda;
    private javax.swing.JPanel cardCarrinho;
    private javax.swing.JPanel cardComedia;
    private javax.swing.JPanel cardDestaquesDeHoje;
    private javax.swing.JPanel cardEducacional;
    private javax.swing.JPanel cardFantasia;
    private javax.swing.JPanel cardFiccao;
    private javax.swing.JPanel cardHistorico;
    private javax.swing.JPanel cardMeuPerfil;
    private javax.swing.JPanel cardRomance;
    private javax.swing.JPanel cardSuspense;
    private javax.swing.JPanel cardTerror;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel painelMutavel;
    // End of variables declaration//GEN-END:variables
}
